"return  { 
"['vweo_sbus1'] =  { 
"    ['name'] = 'vweo_sbus1',  
"    ['model'] = 'vweo_sbus1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_sbus1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_7111'] =  { 
"    ['name'] = 'vweo_7111',  
"    ['model'] = 'vweo_7111',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_7111',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_ardent1'] =  { 
"    ['name'] = 'vweo_ardent1',  
"    ['model'] = 'vweo_ardent1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_ardent1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_blista1'] =  { 
"    ['name'] = 'vweo_blista1',  
"    ['model'] = 'vweo_blista1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_blista1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_boomerang1'] =  { 
"    ['name'] = 'vweo_boomerang1',  
"    ['model'] = 'vweo_boomerang1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_boomerang1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_cw20201'] =  { 
"    ['name'] = 'vweo_cw20201',  
"    ['model'] = 'vweo_cw20201',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_cw20201',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_deluxo1'] =  { 
"    ['name'] = 'vweo_deluxo1',  
"    ['model'] = 'vweo_deluxo1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_deluxo1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_dukes1'] =  { 
"    ['name'] = 'vweo_dukes1',  
"    ['model'] = 'vweo_dukes1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_dukes1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_elegy1'] =  { 
"    ['name'] = 'vweo_elegy1',  
"    ['model'] = 'vweo_elegy1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_elegy1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_elegy2'] =  { 
"    ['name'] = 'vweo_elegy2',  
"    ['model'] = 'vweo_elegy2',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_elegy2',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_elegy3'] =  { 
"    ['name'] = 'vweo_elegy3',  
"    ['model'] = 'vweo_elegy3',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_elegy3',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_emperor1'] =  { 
"    ['name'] = 'vweo_emperor1',  
"    ['model'] = 'vweo_emperor1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_emperor1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_es5501'] =  { 
"    ['name'] = 'vweo_es5501',  
"    ['model'] = 'vweo_es5501',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_es5501',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_flash1'] =  { 
"    ['name'] = 'vweo_flash1',  
"    ['model'] = 'vweo_flash1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_flash1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_fmjgte1'] =  { 
"    ['name'] = 'vweo_fmjgte1',  
"    ['model'] = 'vweo_fmjgte1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_fmjgte1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_fugitive1'] =  { 
"    ['name'] = 'vweo_fugitive1',  
"    ['model'] = 'vweo_fugitive1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_fugitive1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_futo1'] =  { 
"    ['name'] = 'vweo_futo1',  
"    ['model'] = 'vweo_futo1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_futo1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_futo2'] =  { 
"    ['name'] = 'vweo_futo2',  
"    ['model'] = 'vweo_futo2',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_futo2',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_gauntlet1'] =  { 
"    ['name'] = 'vweo_gauntlet1',  
"    ['model'] = 'vweo_gauntlet1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_gauntlet1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_gauntlet2'] =  { 
"    ['name'] = 'vweo_gauntlet2',  
"    ['model'] = 'vweo_gauntlet2',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_gauntlet2',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_hellhound1'] =  { 
"    ['name'] = 'vweo_hellhound1',  
"    ['model'] = 'vweo_hellhound1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_hellhound1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_hpr1'] =  { 
"    ['name'] = 'vweo_hpr1',  
"    ['model'] = 'vweo_hpr1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_hpr1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_infernus1'] =  { 
"    ['name'] = 'vweo_infernus1',  
"    ['model'] = 'vweo_infernus1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_infernus1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_ingot1'] =  { 
"    ['name'] = 'vweo_ingot1',  
"    ['model'] = 'vweo_ingot1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_ingot1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_issi1'] =  { 
"    ['name'] = 'vweo_issi1',  
"    ['model'] = 'vweo_issi1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_issi1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_jv901'] =  { 
"    ['name'] = 'vweo_jv901',  
"    ['model'] = 'vweo_jv901',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_jv901',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_kart1'] =  { 
"    ['name'] = 'vweo_kart1',  
"    ['model'] = 'vweo_kart1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_kart1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_kuruma1'] =  { 
"    ['name'] = 'vweo_kuruma1',  
"    ['model'] = 'vweo_kuruma1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_kuruma1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_kuruma2'] =  { 
"    ['name'] = 'vweo_kuruma2',  
"    ['model'] = 'vweo_kuruma2',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_kuruma2',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_lentus1'] =  { 
"    ['name'] = 'vweo_lentus1',  
"    ['model'] = 'vweo_lentus1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_lentus1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_majimalm1'] =  { 
"    ['name'] = 'vweo_majimalm1',  
"    ['model'] = 'vweo_majimalm1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_majimalm1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_monster1'] =  { 
"    ['name'] = 'vweo_monster1',  
"    ['model'] = 'vweo_monster1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_monster1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_packer1'] =  { 
"    ['name'] = 'vweo_packer1',  
"    ['model'] = 'vweo_packer1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_packer1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_picador1'] =  { 
"    ['name'] = 'vweo_picador1',  
"    ['model'] = 'vweo_picador1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_picador1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_r70k1'] =  { 
"    ['name'] = 'vweo_r70k1',  
"    ['model'] = 'vweo_r70k1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_r70k1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_rapidgte1'] =  { 
"    ['name'] = 'vweo_rapidgte1',  
"    ['model'] = 'vweo_rapidgte1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_rapidgte1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_remower1'] =  { 
"    ['name'] = 'vweo_remower1',  
"    ['model'] = 'vweo_remower1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_remower1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_requiem1'] =  { 
"    ['name'] = 'vweo_requiem1',  
"    ['model'] = 'vweo_requiem1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_requiem1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_sabregt1'] =  { 
"    ['name'] = 'vweo_sabregt1',  
"    ['model'] = 'vweo_sabregt1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_sabregt1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_sbus1'] =  { 
"    ['name'] = 'vweo_sbus1',  
"    ['model'] = 'vweo_sbus1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_sbus1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_sentinel1'] =  { 
"    ['name'] = 'vweo_sentinel1',  
"    ['model'] = 'vweo_sentinel1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_sentinel1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_sentinel2'] =  { 
"    ['name'] = 'vweo_sentinel2',  
"    ['model'] = 'vweo_sentinel2',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_sentinel2',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_spritzer1'] =  { 
"    ['name'] = 'vweo_spritzer1',  
"    ['model'] = 'vweo_spritzer1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_spritzer1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_t201'] =  { 
"    ['name'] = 'vweo_t201',  
"    ['model'] = 'vweo_t201',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_t201',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_torero1'] =  { 
"    ['name'] = 'vweo_torero1',  
"    ['model'] = 'vweo_torero1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_torero1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_verlierer1'] =  { 
"    ['name'] = 'vweo_verlierer1',  
"    ['model'] = 'vweo_verlierer1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_verlierer1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_vigero1'] =  { 
"    ['name'] = 'vweo_vigero1',  
"    ['model'] = 'vweo_vigero1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_vigero1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_youga1'] =  { 
"    ['name'] = 'vweo_youga1',  
"    ['model'] = 'vweo_youga1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_youga1',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_zion1'] =  { 
"    ['name'] = 'vweo_zion1',  
"    ['model'] = 'vweo_zion1',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_zion1',  
"    ['shop'] = 'tuner',  
"},  

"['vweo_zion2'] =  { 
"    ['name'] = 'vweo_zion2',  
"    ['model'] = 'vweo_zion2',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_zion2',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_zr3501'] =  { 
"    ['name'] = 'vweo_zr3501',  
"    ['model'] = 'vweo_zr3501',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_zr3501',  
"    ['shop'] = 'tuner',  
"},  
"['vweo_zr3801'] =  { 
"    ['name'] = 'vweo_zr3801',  
"    ['model'] = 'vweo_zr3801',  
"    ['price'] = 2000000,  
"    ['category'] = 'addons',  
"    ['categoryLabel'] = 'addons',  
"    ['hash'] = 'vweo_zr3801',  
"    ['shop'] = 'tuner',  
"},  
"}" 
